-----------------------------------------------------------------------------
/* 테이블 초기화 구문 */
-----------------------------------------------------------------------------
DROP TABLE TB_GENRE CASCADE CONSTRAINTS;
DROP TABLE TB_SERIALIZATION CASCADE CONSTRAINTS;
DROP TABLE TB_WEBTOON CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_GENRE_CODE;
DROP SEQUENCE SEQ_SERIAL_CODE;
DROP SEQUENCE SEQ_WEBTOON_NO;
-----------------------------------------------------------------------------
/* SEQUENCE 생성 */
-----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_GENRE_CODE START WITH 1;
CREATE SEQUENCE SEQ_SERIAL_CODE START WITH 1;
CREATE SEQUENCE SEQ_WEBTOON_NO START WITH 1;
-----------------------------------------------------------------------------
/* TB_SERIALIZATION */
-----------------------------------------------------------------------------
CREATE TABLE TB_SERIALIZATION(
    SERIAL_CODE NUMBER,
    SERIAL_DATE VARCHAR(20),
    SERIAL_STATUS VARCHAR(20)
);
ALTER TABLE C##WEBTOON.TB_SERIALIZATION ADD CONSTRAINT PK_SC PRIMARY KEY (SERIAL_CODE);

COMMENT ON COLUMN C##WEBTOON.TB_SERIALIZATION.SERIAL_CODE IS '연재코드';
COMMENT ON COLUMN C##WEBTOON.TB_SERIALIZATION.SERIAL_DATE IS '연재일';
COMMENT ON COLUMN C##WEBTOON.TB_SERIALIZATION.SERIAL_STATUS IS '연재상태';

INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '월', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '화', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '수', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '목', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '금', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '토', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, '일', 'CON');
INSERT INTO TB_SERIALIZATION VALUES (SEQ_SERIAL_CODE.NEXTVAL, NULL, 'FIN');

-----------------------------------------------------------------------------
/* TB_ GENRE */
-----------------------------------------------------------------------------
CREATE TABLE C##WEBTOON.TB_GENRE(
    GENRE_CODE NUMBER,
    GENRE_NAME VARCHAR(20)
);

ALTER TABLE C##WEBTOON.TB_GENRE ADD CONSTRAINT PK_GC PRIMARY KEY (GENRE_CODE);

COMMENT ON COLUMN C##WEBTOON.TB_GENRE.GENRE_CODE IS '장르번호';
COMMENT ON COLUMN C##WEBTOON.TB_GENRE.GENRE_NAME IS '장르이름';

INSERT INTO C##WEBTOON.TB_GENRE (GENRE_CODE, GENRE_NAME) VALUES (SEQ_GENRE_CODE.NEXTVAL, '무협');
INSERT INTO C##WEBTOON.TB_GENRE (GENRE_CODE, GENRE_NAME) VALUES (SEQ_GENRE_CODE.NEXTVAL, '일상');
INSERT INTO C##WEBTOON.TB_GENRE (GENRE_CODE, GENRE_NAME) VALUES (SEQ_GENRE_CODE.NEXTVAL, '판타지');
INSERT INTO C##WEBTOON.TB_GENRE (GENRE_CODE, GENRE_NAME) VALUES (SEQ_GENRE_CODE.NEXTVAL, '로맨스');
INSERT INTO C##WEBTOON.TB_GENRE (GENRE_CODE, GENRE_NAME) VALUES (SEQ_GENRE_CODE.NEXTVAL, '스포츠');


-----------------------------------------------------------------------------
/* TB_WEBTOON */
-----------------------------------------------------------------------------
CREATE TABLE "C##WEBTOON"."TB_WEBTOON"(
    WEBTOON_NO NUMBER,
    WEBTOON_NAME VARCHAR(40) NOT NULL, 
    SERIAL_CODE NUMBER,
    WRITER VARCHAR(20),
    ILLUSTRATOR VARCHAR(20),                                                                                   
    GENRE_CODE NUMBER
);

ALTER TABLE C##WEBTOON.TB_WEBTOON ADD CONSTRAINT PK_WN PRIMARY KEY (WEBTOON_NO); 
ALTER TABLE C##WEBTOON.TB_WEBTOON ADD CONSTRAINT FK_SC FOREIGN KEY (SERIAL_CODE) REFERENCES TB_SERIALIZATION(SERIAL_CODE);
ALTER TABLE C##WEBTOON.TB_WEBTOON ADD CONSTRAINT FK_GC FOREIGN KEY (GENRE_CODE) REFERENCES TB_GENRE(GENRE_CODE); 

COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.WEBTOON_NO IS '웹툰번호';
COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.WEBTOON_NAME IS '웹툰명';
COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.SERIAL_CODE IS '연재코드';
COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.WRITER IS '글작가';
COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.ILLUSTRATOR IS '그림작가';
COMMENT ON COLUMN C##WEBTOON.TB_WEBTOON.GENRE_CODE IS '장르번호';

INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '아비무쌍', 2, '이현석', '노경찬', 1); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '화산귀환', 3, '비가', 'LICO', 1);
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '북검전기', 3, '우각', '해민', 1); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '홍도', 8, 'SNOWY_SOUL', 'SNOWY_SOUL', 1); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '가우스전자', 8, '곽백수', '곽백수', 2); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '마음의소리', 8, '조석', '조석', 2); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '질풍기획', 8, '이현민', '이현민', 2); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '신의탑', 1, 'SIU', 'SIU', 3); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '나혼자만레벨업', 8, '현군', '장성락', 3); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '전지적독자시점', 3, '싱숑', '슬리피-C', 3);
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '조의영역', 8, '조석', '조석', 3); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '치즈인더트랩', 8, '순끼', '순끼', 4); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '연애혁명', 4, '232', '232', 4); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '세기말풋사과보습학원', 5,'순끼', '순끼', 4); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '빌드업', 3, '911', '911', 5); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '가비지타임', 7, '2사장', '2사장', 5); 
INSERT INTO TB_WEBTOON VALUES (SEQ_WEBTOON_NO.NEXTVAL, '프레너미', 4, '돌석', '돌석', 5); 
